spring:
  application:
    name: auth-service
    admin:
      default:
        username: admin
        password: admin
        email: admin@admin.com
  config:
    import:
    - optional:file:.env[.properties]
    - 'classpath:web.yml'
    - 'classpath:eureka.yml'
    - 'classpath:database.yml'
    - 'classpath:kafka.yml'
logging:
  level:
    root: ${LOGGING_LEVEL:info}

jwt:
  secret: ${JWT_SECRET:defaultDevSecretKeyThatIsLongEnough_please_replace}
  access-exp: ${ACCESS_EXP:900000}
  refresh-exp: ${REFRESH_EXP:604800000}