spring:
  kafka:
    producer:
      bootstrap-servers: ${BOOTSTRAP_SERVER:localhost:9092}

      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      acks: all

      properties:
        enable.idempotence: true